theme: jekyll-theme-minimal
name: Meagan E Crowther
title: null
description: Professional Website - Meagan Crowther
future: true
show_downloads: false
google_analytics: 
github:
  repository_url: https://github.com/meagan-crowther/meagan-crowther.github.io